### ISSUE TITLE
Reverse routing

### ISSUE THREAD

**Issue by mofr** [mofr/winter#117]
It should look like:
```
winter.router.reverse(SomeController.some_method, some_arg='some_value')
```
reverse should return rendered url template.

**Additional context**
Spring implementation: https://github.com/resthub/springmvc-router#reverse-routing
Django implementation: https://docs.djangoproject.com/en/2.2/ref/urlresolvers/#reverse

**Comment by berenda-andrey** [comment]
Done in https://github.com/mofr/winter/pull/121
