### ISSUE TITLE
Make @winter.throws(...) catch derived exceptions

### ISSUE THREAD

**Issue by EvgenySmekalin** [mofr/winter#142]
When I was trying to use `@winter.throws(ParentException)` the derived exception from `ParentException` was not caught. Produce duplicated code using the same handler classes  

It will be great to have the possibility to catch all exception derived from `ParentException` either:
- by catching just parent exception
- by passing a list of exceptions to `@winter.throws`

**Comment by berenda-andrey** [comment]
it seems evetything is good. See my PR (https://github.com/mofr/winter/pull/143).

**Comment by mofr** [comment]
@EvgenySmekalin Please approve that the problem is fixed and I'll go and close the issue.

**Comment by berenda-andrey** [comment]
@EvgenySmekalin ping

**Comment by EvgenySmekalin** [comment]
Sorry for the big delay, I'm missed all notifications. I need some time to test it again on project.
I'll do it as soon as I can and make a comment here about the results

**Comment by EvgenySmekalin** [comment]
It seems like I'm made a mistake in my code. The package works well
