### ISSUE TITLE
Generate response body schema based on dataclasses

### ISSUE THREAD

**Issue by mofr** [mofr/winter#22]
Consider adding following methods for this purpose:
* `ControllerMethodInspector.inspect_response_body`
* `ControllerMethodInspector.inspect_request_body`

**Comment by mofr** [comment]
Also, consider allowing using dataclasses as DRF serializers fields.

**Comment by berenda-andrey** [comment]
Done only for response https://github.com/mofr/winter/pull/25

**Comment by mofr** [comment]
@berenda-andrey Implementing it for request body it's not an issue as well, but we need to think about validation, right?

**Comment by berenda-andrey** [comment]
@mofr Yes, we need to think about it

**Comment by mofr** [comment]
Created #43 for request body and left this one for response body only.
