### ISSUE TITLE
Invalid swagger type for path parameters declared at controller level

### ISSUE THREAD

**Issue by mofr** [mofr/winter#31]
**Description**
When `winter.route` is used on a class with URL containing variables swagger shows wrong type (always string).

**Expected behavior**
Winter should inspect the type of such parameters according to type annotation in a method.

**Code snippets**
`param` will have a string type reported in swagger, while integer is expected.
```
@winter.controller
@winter.route('/test/{param}/')
class SomeContoller:
    @winter.route_get()
    def test(param: int):
        pass
```

**Environment:**
 - All python versions
 - Winter version 1.2.0

**Comment by berenda-andrey** [comment]
This is done in https://github.com/mofr/winter/commit/a63178703f0623d7d1bee250b28757da20201252
